baseURL = "http://192.168.99.100:1313/"
title = "Chao Li"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = ""

[params]
  # Enables syntax highlighting
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = ""
  github = "xingyulc"
  email = "132128550li@gmail.com"
  gaid = ""
  twitter = ""
  medium = ""